---
swagger: "2.0"
info:
  description: "An API that provides airport code information"
  version: "1.0.0"
  title: "Airport Code Lookup"
  contact:
    email: "reselbob@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/CogArtTech6/Simple/1.0.0"
tags:
- name: "admins"
  description: "Secured Admin-only calls"
- name: "developers"
  description: "Operations available to regular developers"
schemes:
- "https"
- "http"
paths:
  /airportCodes:
    get:
      tags:
      - "developers"
      summary: "gets all airport codes"
      description: "Gets all the airport codes stored in the system\n"
      operationId: "getAirportCodes"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "search results matching criteria"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/AirportCode"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "Developers"
  /airportCodes/{code}:
    get:
      tags:
      - "developers"
      summary: "gets all airport codes"
      description: "Gets airport information that corresponds to the submitted aiport\
        \ code system\n"
      operationId: "getAirportCode"
      produces:
      - "application/json"
      parameters:
      - name: "code"
        in: "path"
        description: "The aiport code to lookup"
        required: true
        type: "string"
      responses:
        200:
          description: "the result that corresponds to the submitted airport code"
          schema:
            type: "object"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "Developers"
  /airportCodes/search:
    get:
      tags:
      - "developers"
      summary: "gets all airport codes that corresponds to the search term"
      description: "Gets airport information that corresponds to the submitted search\
        \ term\n"
      operationId: "searchAirportCodes"
      produces:
      - "application/json"
      parameters:
      - name: "searchterm"
        in: "query"
        description: "searches term to process"
        required: true
        type: "string"
      responses:
        200:
          description: "the result that corresponds to the submitted airport code"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/AirportCode"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "Developers"
definitions:
  AirportCode:
    type: "object"
    required:
    - "airport"
    - "code"
    properties:
      airport:
        type: "string"
        example: "Los Angeles International Aiport"
      code:
        type: "string"
        example: "LAX"
    example:
      code: "LAX"
      airport: "Los Angeles International Aiport"
